version: "3"
services:
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3009:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules #ignore this
            - ./backend:/app
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

            - JWT_SECRET=${JWT_SECRET}

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app

        environment:
            - REACT_APP_BE_URL=${REACT_APP_BE_URL}
