apiVersion: apps/v1
kind: Deployment
metadata:
    name: li-client-deployment
    namespace: linkedin
spec:
    replicas: 2

    selector:
        matchLabels:
            component: web

    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: orhanors/linkedin-client
                  ports:
                      - containerPort: 3000
                  env:
                      - name: REACT_APP_BE_URL
                        value: /api
