apiVersion: apps/v1
kind: Deployment
metadata:
    name: li-server-deployment
    namespace: linkedin

spec:
    replicas: 2

    selector:
        matchLabels:
            component: server

    template:
        metadata:
            labels:
                component: server

        spec:
            containers:
                - name: server
                  image: orhanors/linkedin-server
                  ports:
                      - containerPort: 3001
                  env:
                      - name: CLOUDINARY_CLOUD_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: linkedin-configmap
                                key: cloudinary-cloud-name

                      - name: CLOUDINARY_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: cloudinary-api-key
                                key: CLOUDINARY_API_KEY

                      - name: CLOUDINARY_API_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: cloudinary-api-secret
                                key: CLOUDINARY_API_SECRET

                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_SECRET

                      - name: MONGODB_URI
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-uri
                                key: MONGODB_URI
